name: Appointment Check

on:
  schedule:
    - cron: "5 * * * 1-5"

jobs:
  check:
    name: Check the embassy for open appointments
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run appointment checker
        run: node index.js
        env:
          INPUT_RECORD_NUMBER: ${{secrets.RECORD_NUMBER}}
          INPUT_RECORD_AUTH_ANSWER: ${{secrets.RECORD_AUTH_ANSWER}}
          INPUT_MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          INPUT_MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
          INPUT_MAIL_TO: ${{secrets.MAIL_TO}}
