name: CN Embassy AU Appointments Check

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * 0-5"

jobs:
  check:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - run: node index.js
        env:
          INPUT_RECORD_NUMBER: ${{ secrets.RECORD_NUMBER }}
          INPUT_RECORD_AUTH_ANSWER: ${{ secrets.RECORD_AUTH_ANSWER }}
          INPUT_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          INPUT_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          INPUT_MAIL_TO: ${{ secrets.MAIL_TO }}
